# Generated by Django 4.1.3 on 2022-12-25 10:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('PfP', models.URLField()),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='PhoneNumber incorect', regex='0\\s*(5|6|7)(\\s*\\d){8}\\s*')])),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PubDate', models.DateTimeField()),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Price', models.PositiveBigIntegerField()),
                ('Type', models.IntegerField()),
                ('Category', models.IntegerField()),
                ('Position', models.CharField(max_length=255)),
                ('Status', models.IntegerField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.user')),
            ],
        ),
    ]
