# Generated by Django 4.0 on 2023-01-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.message')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.user')),
            ],
        ),
    ]
