# Generated by Django 4.1.3 on 2022-12-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='PfP',
            field=models.URLField(max_length=250),
        ),
    ]
