# Generated by Django 4.1.4 on 2023-01-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_channel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='Area',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
